
@echo on
setlocal enabledelayedexpansion

@REM NOTE: This script expects the ssh to be already configured for REMOTE_A and REMOTE_B

REM Personal access token with "repo" scope 
SET PAT_A="personal_access_token_for_account_a"
SET PAT_B="personal_access_token_for_account_b"
SET REMOTE_A=remote_a
SET REMOTE_B=remote_b

REM Define organization name
SET ORG=organisation

REM Get repository names using curl and jq
curl -H "Authorization: token %PAT_A%" "https://api.github.com/orgs/%ORG%/repos?type=private&per_page=100" | jq -r ".[].name" > repos.txt

for /F "tokens=*" %%A in (repos.txt) do (

  REM Create new repository with same name in account B
  echo "Creating %%A in account %REMOTE_B%..."
  curl -u "%REMOTE_B%:%PAT_B%" -X POST https://api.github.com/user/repos -d "{\"name\": \"%%A\", \"private\": true}"
  echo "finished Creating %%A in account %REMOTE_B%..."

  echo "Cloning %REMOTE_A%:%ORG%/%%A from organization..."
  REM Clone the repository from organization
  git clone git@%REMOTE_A%:%ORG%/%%A.git
  cd %%A
  echo "Finished Cloning %REMOTE_A%:%ORG%/%%A from organization..."

  REM Add remote for account B repository
  git remote add %REMOTE_B% git@github.com:%REMOTE_B%/%%A.git
  git fetch origin

  REM Push main branch to account B
  git push %REMOTE_B%

  curl -H "Authorization: token %PAT_A%" "https://api.github.com/repos/%ORG%/%%A/branches" | jq -r ".[].name" > branches.txt
  echo REM "Syncing script automatically generated by %~dp0" > %cd%\sync.cmd
  echo git fetch origin >> %cd%\sync.cmd
  for /F "tokens=*" %%B in (branches.txt) do (
    git checkout -b %%B origin/%%B
    git push %REMOTE_B%

    echo. >> %cd%\sync.cmd
    echo REM "--------------Syncing %%A:%%B--------------" >> %cd%\sync.cmd
    echo cd %cd%\%%A >> %cd%\sync.cmd
    echo git checkout %%B >> %cd%\sync.cmd
    echo git pull origin %%B >> %cd%\sync.cmd
    echo git push %REMOTE_B% %%B >> %cd%\sync.cmd
    echo. >> %cd%\sync.cmd
  )

  echo pause >> %cd%\sync.cmd

  REM Remove the local clone (optional)
  REM RD /S /Q %%A

)

ECHO All repositories processed!
pause
